### ISSUE TITLE
Adding more datasets

### ISSUE THREAD

**Issue by freakeinstein** [indicnlpweb/indicnlp_catalog#1]
Dialogflow Smalltalk Dataset - Malayalam: https://github.com/a-mma/indic_casual_dialogs_dataset
Named entities dataset - Malayalam news papers and Wikipedia: https://github.com/a-mma/NER_Open_Data

**Comment by anoopkunchukuttan** [comment]
Thanks for sharing the datasets. I will add it to the catalog.

**Comment by anoopkunchukuttan** [comment]
Added
