### ISSUE TITLE
Monolingual Datasets for some indian languages

### ISSUE THREAD

**Issue by deciphyre** [indicnlpweb/indicnlp_catalog#2]
Hi,
There are some monolingual corpora available for Indian languages at this [cite](http://wortschatz.uni-leipzig.de/en/download/) in **All Languages**, corresponding paper is [here](http://www.lrec-conf.org/proceedings/lrec2012/pdf/327_Paper.pdf).

**Comment by anoopkunchukuttan** [comment]
Thanks, added the corpus.
