### ISSUE TITLE
wikipron Indian Languages datasets

### ISSUE THREAD

**Issue by warnak** [indicnlpweb/indicnlp_catalog#35]
A possible addition to the library could be the 2020 wikipron API's pre scraped Indian Languages' datasets of Phonemic and Phonetic IPA transcription of pronunciations.
It also syllabified and tokenized into various phonemes.
Hindi has 8K+ words, others have less than 2K currently.

**Comment by anoopkunchukuttan** [comment]
Thanks for pointing out. I will add this.

**Comment by anoopkunchukuttan** [comment]
https://pypi.org/project/wikipron/

Jackson L. Lee, Lucas F.E. Ashby, M. Elizabeth Garza, Yeonju Lee-Sikka, Sean Miller, Alan Wong, Arya D. McCarthy, and Kyle Gorman (2020). Massively multilingual pronunciation mining with WikiPron. In LREC, to appear.

https://www.aclweb.org/anthology/2020.lrec-1.521/

**Comment by anoopkunchukuttan** [comment]
Done
