### ISSUE TITLE
Large twitter datasets for Telugu and Hindi

### ISSUE THREAD

**Issue by bedapudi6788** [indicnlpweb/indicnlp_catalog#4]
Hi, 
https://github.com/bedapudi6788/LOIT in this repo I added large twitter datasets for telugu (7.9 million) and hindi (17.6 million) and fasttext skipgram and cbow word vectors for the same.

**Comment by anoopkunchukuttan** [comment]
Thanks Praneeth, I have added the record to the catalog under monolingual corpora.
