### ISSUE TITLE
Add CLTK

### ISSUE THREAD

**Issue by parmarsuraj99** [indicnlpweb/indicnlp_catalog#8]
First of all, Thank you very much for making it available. Found what i was looking for.

I would suggest to add 
[CLTK](https://github.com/cltk) library. 
which has so many languages corpus and utilities for formats.

**Comment by anoopkunchukuttan** [comment]
Thanks for pointing out and glad that this catalog helped. Added. Parts of CLTK use the IndicNLP library.
