### ISSUE TITLE
Huggingface Language models - Albert Base for Sanskrit

### ISSUE THREAD

**Issue by parmarsuraj99** [indicnlpweb/indicnlp_catalog#9]
I have trained a language model on Sanskrit wikipedia.
and uploaded on HuggingFace models. 

[Albert Base Sanskrit](https://huggingface.co/surajp/albert-base-sanskrit).

This can be used to get Word Embeddings from sentences.

**Comment by anoopkunchukuttan** [comment]
That is great! Added to the catalog.

**Comment by parmarsuraj99** [comment]
Thank you very much! I will be training and sharing more models on Indian Languages
